// ActionTypes
export const StoggleActionTypes = {
  STOGGLE_REQUEST_ADD: '@@stoggle/STOGGLE_REQUEST_ADD',
  STOGGLE_REQUEST_DELETE: '@@stoggle/STOGGLE_REQUEST_DELETE',
  STOGGLE_REQUEST_TOGGLE: '@@stoggle/STOGGLE_REQUEST_TOGGLE',
  STOGGLE_REQUEST_GET: '@@stoggle/STOGGLE_REQUEST_GET',
  STOGGLE_FILTER_ALL: '@@stoggle/STOGGLE_FILTER_ALL',
  STOGGLE_FILTER_AVAILABLE: '@@stoggle/STOGGLE_FITER_AVAILABLE',
  STOGGLE_FILTER_BUSY: '@@stoggle/STOGGLE_FILTER_BUSY'
}
