// ActionTypes
export const StoggleActionTypes = {
  STOGGLE_REQUEST_GET_USERINFO: '@@stoggle/STOGGLE_REQUEST_GET_USERINFO',
  STOGGLE_REQUEST_GET: '@@stoggle/STOGGLE_REQUEST_GET',
  STOGGLE_REQUEST_ADD: '@@stoggle/STOGGLE_REQUEST_ADD',
  STOGGLE_REQUEST_DELETE: '@@stoggle/STOGGLE_REQUEST_DELETE',
  STOGGLE_REQUEST_TOGGLE: '@@stoggle/STOGGLE_REQUEST_TOGGLE',

  STOGGLE_SUCCESS_GET_USERINFO: '@@stoggle/STOGGLE_SUCCESS_GET_USERINFO',
  STOGGLE_SUCCESS_GET: '@@stoggle/STOGGLE_SUCCESS_GET',
  STOGGLE_SUCCESS_ADD: '@@stoggle/STOGGLE_SUCCESS_ADD',
  STOGGLE_SUCCESS_DELETE: '@@stoggle/STOGGLE_SUCCESS_DELETE',
  STOGGLE_SUCCESS_TOGGLE: '@@stoggle/STOGGLE_SUCCESS_TOGGLE',

  STOGGLE_FAILURE: '@@stoggle/STOGGLE_FAILURE',

  STOGGLE_FILTER_ALL: '@@stoggle/STOGGLE_FILTER_ALL',
  STOGGLE_FILTER_AVAILABLE: '@@stoggle/STOGGLE_FITER_AVAILABLE',
  STOGGLE_FILTER_BUSY: '@@stoggle/STOGGLE_FILTER_BUSY'
}
